### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by Ragazzoforte** [rene-d/netatmo#12]
![Schermopname (156)](https://user-images.githubusercontent.com/60049220/107654690-2f005a80-6c83-11eb-9064-476c3b35da6e.png)

Hello,
I am trying to read the temperature from my netatmo thermostat. However, I run into this problem, do you know what the problem could be?

**Comment by rene-d** [comment]
Try to remove the `'device'` element in the dict.

However, when I use a bad device_id, I get the following message:
```text
error {'code': 21, 'message': 'device id is invalid'} https://api.netatmo.com/api/getstationsdata
```
and not `Device not found`. This message comes from Netatmo servers, not from the Python package.

**Comment by rene-d** [comment]
Moreover, this library has not been tested with other Netatmo devices than the weather station (especially
 the thermostat). You can add support for it if you dare.
