### ISSUE TITLE
Invalid client

### ISSUE THREAD

**Issue by fmarzocca** [rene-d/netatmo#3]
Hi,

after configuration, I ran "test", but I got this message:

```
./netatmo.py test
error invalid_client https://api.netatmo.com/oauth2/token
netatmo.py : ERROR
```

the configuration file is:

```
username: <username>
password: <password>
client_id: <client_id>
client_secret: <client_secret>
default_device_id: 70:ee:50:37:15:1e
```

**Comment by rene-d** [comment]
Hi Fabio,

The ~/.netatmorc file should look like this:
```
[netatmo]
username = <username>
password = <password>
client_id = <client_id>
client_secret = <client_secret>
default_device_id = 70:ee:50:37:15:1e
```

On which platform do you run the program ? 

Regards,

**Comment by fmarzocca** [comment]
Hi Rene,

yes, I confirm the config file is as you reported.

I have tested it on MacOS and on Raspbian Linux

**Comment by fmarzocca** [comment]
My BAD!
Sorry, I was not typing the correct client_ID.

**Comment by rene-d** [comment]
Nessun problema :)

Thanks for your interest!
