### ISSUE TITLE
csv-files: make it excel-compatible and quote everything

### ISSUE THREAD

**Issue by ffischer1984** [rene-d/netatmo#7]
If you open the csv file in excel some data will not be displayed because excel confuses that only strings are quoted. Tested with Excel 2010
![image](https://user-images.githubusercontent.com/8037710/94136582-6fdb0c80-fe65-11ea-9385-fe311a1d53b1.png)

**Comment by rene-d** [comment]
You can force the type of fields when importing a CSV into Excel
